config/routes.rb
Rails.application.routes.draw do
  resources :proveedors
  resources :entradas
  resources :salidas
  resources :productos
  devise_for :users
	 get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
end

app/controllers/proveedors_controller.rb
class ProveedorsController < ApplicationController
  before_action :set_proveedor, only: [:show, :edit, :update, :destroy]

  # GET /proveedors
  # GET /proveedors.json
  def index
    @proveedors = Proveedor.all
  end

  # GET /proveedors/1
  # GET /proveedors/1.json
  def show
  end

  # GET /proveedors/new
  def new
    @proveedor = Proveedor.new
  end

  # GET /proveedors/1/edit
  def edit
  end

  # POST /proveedors
  # POST /proveedors.json
  def create
    @proveedor = Proveedor.new(proveedor_params)

    respond_to do |format|
      if @proveedor.save
        format.html { redirect_to @proveedor, notice: 'Proveedor was successfully created.' }
        format.json { render :show, status: :created, location: @proveedor }
      else
        format.html { render :new }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedors/1
  # PATCH/PUT /proveedors/1.json
  def update
    respond_to do |format|
      if @proveedor.update(proveedor_params)
        format.html { redirect_to @proveedor, notice: 'Proveedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @proveedor }
      else
        format.html { render :edit }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedors/1
  # DELETE /proveedors/1.json
  def destroy
    @proveedor.destroy
    respond_to do |format|
      format.html { redirect_to proveedors_url, notice: 'Proveedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedor
      @proveedor = Proveedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedor_params
      params.require(:proveedor).permit(:provedor, :contacto)
    end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/proveedors/_form.html.erb
<%= form_for(proveedor) do |f| %>
  <% if proveedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedor.errors.count, "error") %> prohibited this proveedor from being saved:</h2>

      <ul>
      <% proveedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provedor %>
    <%= f.text_field :provedor %>
  </div>

  <div class="field">
    <%= f.label :contacto %>
    <%= f.text_area :contacto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proveedors/edit.html.erb
<h1>Editing Proveedor</h1>

<%= render 'form', proveedor: @proveedor %>

<%= link_to 'Show', @proveedor %> |
<%= link_to 'Back', proveedors_path %>

app/views/proveedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedors</h1>

<table>
  <thead>
    <tr>
      <th>Provedor</th>
      <th>Contacto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveedors.each do |proveedor| %>
      <tr>
        <td><%= proveedor.provedor %></td>
        <td><%= proveedor.contacto %></td>
        <td><%= link_to 'Show', proveedor %></td>
        <td><%= link_to 'Edit', edit_proveedor_path(proveedor) %></td>
        <td><%= link_to 'Destroy', proveedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proveedor', new_proveedor_path %>

app/views/proveedors/new.html.erb
<h1>New Proveedor</h1>

<%= render 'form', proveedor: @proveedor %>

<%= link_to 'Back', proveedors_path %>

app/views/proveedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provedor:</strong>
  <%= @proveedor.provedor %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @proveedor.contacto %>
</p>

<%= link_to 'Edit', edit_proveedor_path(@proveedor) %> |
<%= link_to 'Back', proveedors_path %>