config/routes.rb
Rails.application.routes.draw do
  resources :proveedors
  resources :entradas
  resources :salidas
  resources :productos
  devise_for :users
	 get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entrada.rb
class Entrada < ApplicationRecord
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada was successfully created.' }
        format.json { render :show, status: :created, location: @entrada }
      else
        format.html { render :new }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrada }
      else
        format.html { render :edit }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url, notice: 'Entrada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:fecha, :remision, :articulo, :cantidad, :recibe, :proveedor, :autoriza, :solicita)
    end
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/views/entradas/_form.html.erb
<%= form_for(entrada) do |f| %>
  <% if entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entrada.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% entrada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.date_select :fecha %>
  </div>

  <div class="field">
    <%= f.label :remision %>
    <%= f.number_field :remision %>
  </div>

  <div class="field">
    <%= f.label :articulo %>
    <%= f.text_field :articulo %>
  </div>

  <div class="field">
    <%= f.label :cantidad %>
    <%= f.text_field :cantidad %>
  </div>

  <div class="field">
    <%= f.label :recibe %>
    <%= f.text_field :recibe %>
  </div>

  <div class="field">
    <%= f.label :proveedor %>
    <%= f.text_field :proveedor %>
  </div>

  <div class="field">
    <%= f.label :autoriza %>
    <%= f.text_field :autoriza %>
  </div>

  <div class="field">
    <%= f.label :solicita %>
    <%= f.text_field :solicita %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entradas/edit.html.erb
<h1>Editing Entrada</h1>

<%= render 'form', entrada: @entrada %>

<%= link_to 'Show', @entrada %> |
<%= link_to 'Back', entradas_path %>

app/views/entradas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entradas</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Remision</th>
      <th>Articulo</th>
      <th>Cantidad</th>
      <th>Recibe</th>
      <th>Proveedor</th>
      <th>Autoriza</th>
      <th>Solicita</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.fecha %></td>
        <td><%= entrada.remision %></td>
        <td><%= entrada.articulo %></td>
        <td><%= entrada.cantidad %></td>
        <td><%= entrada.recibe %></td>
        <td><%= entrada.proveedor %></td>
        <td><%= entrada.autoriza %></td>
        <td><%= entrada.solicita %></td>
        <td><%= link_to 'Show', entrada %></td>
        <td><%= link_to 'Edit', edit_entrada_path(entrada) %></td>
        <td><%= link_to 'Destroy', entrada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entrada', new_entrada_path %>

app/views/entradas/new.html.erb
<h1>New Entrada</h1>

<%= render 'form', entrada: @entrada %>

<%= link_to 'Back', entradas_path %>

app/views/entradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @entrada.fecha %>
</p>

<p>
  <strong>Remision:</strong>
  <%= @entrada.remision %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @entrada.articulo %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @entrada.cantidad %>
</p>

<p>
  <strong>Recibe:</strong>
  <%= @entrada.recibe %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @entrada.proveedor %>
</p>

<p>
  <strong>Autoriza:</strong>
  <%= @entrada.autoriza %>
</p>

<p>
  <strong>Solicita:</strong>
  <%= @entrada.solicita %>
</p>

<%= link_to 'Edit', edit_entrada_path(@entrada) %> |
<%= link_to 'Back', entradas_path %>