config/routes.rb
Rails.application.routes.draw do
  resources :proveedors
  resources :entradas
  resources :salidas
  resources :productos
  devise_for :users
	 get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/producto.rb
class Producto < ApplicationRecord
	has_and_belongs_to_many :salidas
  	before_validation :stock


  	def stock
  		if existencia >= stockmin
  			@producto = Producto.new

  		 else existencia < stockmin
  		 	self.errors.add("no se pudo procesar")
  		end
  	end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:articulo, :existencia, :stockmin, :stockmax, :disponibles)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(producto) do |f| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :articulo %>
    <%= f.text_field :articulo %>
  </div>

  <div class="field">
    <%= f.label :existencia %>
    <%= f.number_field :existencia %>
  </div>

  <div class="field">
    <%= f.label :stockmin %>
    <%= f.number_field :stockmin %>
  </div>

  <div class="field">
    <%= f.label :stockmax %>
    <%= f.number_field :stockmax %>
  </div>

  <div class="field">
    <%= f.label :disponibles %>
    <%= f.text_field :disponibles %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Articulo</th>
      <th>Existencia</th>
      <th>Stockmin</th>
      <th>Stockmax</th>
      <th>Disponibles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.articulo %></td>
        <td><%= producto.existencia %></td>
        <td><%= producto.stockmin %></td>
        <td><%= producto.stockmax %></td>
        <td><%= producto.disponibles %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Articulo:</strong>
  <%= @producto.articulo %>
</p>

<p>
  <strong>Existencia:</strong>
  <%= @producto.existencia %>
</p>

<p>
  <strong>Stockmin:</strong>
  <%= @producto.stockmin %>
</p>

<p>
  <strong>Stockmax:</strong>
  <%= @producto.stockmax %>
</p>

<p>
  <strong>Disponibles:</strong>
  <%= @producto.disponibles %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>